version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8787:8787"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/movies
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
